#cloud-config
users:
   - name: ubuntu
     ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2vj5ISvPVfyCCOI8dZFagrhEjwPTFletKbYuNiTIHTMKp91Q6lGQOy7geg4vVgRk7mxcZrEiLxHNrv/KqTyZpleIBgLYGnQB9u4vwNgNk6ORrODKItKKDLV3eNCCYZog8y5LGukHU5DGUgLjqiscQ16Y+TzkXH925riL2gvCSw1lQTy3rpiiW5RQwL1tAl29qZj2lD8r5Kp8YWwm98SdueYLFkTbd9SKSWZXkIewnePRD77O1dqGzafM3371+a2y2KuJjgPDyKFe8Dc/dXP3bocsJqPBjtrBHw6bDmH/xA0CLCn72sUE0fWrqxKSMFO87nFXzW6yXn+pRtZbIXC+b pratyushmittal@gmail.com
     lock_passwd: True
     sudo: ALL=(ALL) NOPASSWD:ALL
     groups: sudo
     shell: /bin/bash

# Set timezone
timezone: Asia/Kolkata

packages:
   - landscape-common
   - curl

# for docker packages
packages:
   - apt-transport-https
   - ca-certificates
   - software-properties-common

# firewall
runcmd:
   # Firewall
   - sudo ufw allow ssh
   - sudo ufw limit ssh
   - sudo ufw enable

# postfix
runcmd:
   - export HOSTNAME=$(curl -s http://169.254.169.254/metadata/v1/hostname)
   - sudo debconf-set-selections <<< "postfix postfix/mailname string $HOSTNAME"
   - sudo debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
   - sudo apt-get install -y postfix mailutils

# DKIM Keys
runcmd:
   - sudo apt-get install -y opendkim opendkim-tools
   - sudo mkdir -p /etc/opendkim/keys/$HOSTNAME
   - cd /etc/opendkim/keys/$HOSTNAME
   - sudo opendkim-genkey -s mail -d $HOSTNAME
   - sudo chown opendkim:opendkim mail.private

# Install Docker
runcmd:
   - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
   - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
   - sudo apt-get update
   - sudo apt-get -y install docker-ce

# Manage docker as non-root
runcmd:
   - sudo groupadd docker
   - sudo usermod -aG docker ubuntu

# Start docker on startup
runcmd:
   - sudo systemctl enable docker

# Install docker-compose
runcmd:
   - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
   - sudo chmod +x /usr/local/bin/docker-compose

# Add docker command-line completion
runcmd:
   - sudo curl -L https://raw.githubusercontent.com/docker/compose/1.24.1/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose
